"""create integration messages

THROWAWAY: integration_messages backs the manual end-to-end test at
/integration-test and carries no domain meaning. When that feature is
removed, add a matching migration that drops the table.

Revision ID: 01e17693a0e6
Revises:
Create Date: 2026-08-19 00:40:25.081987+00:00

"""

from typing import Optional, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01e17693a0e6"
down_revision: Optional[str] = None
branch_labels: Union[str, tuple, None] = None
depends_on: Union[str, tuple, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSED')",
            name="integration_messages_status_valid",
        ),
        sa.CheckConstraint(
            "length(body) BETWEEN 1 AND 280", name="integration_messages_body_length"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_integration_messages_created_at",
        "integration_messages",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_integration_messages_created_at", table_name="integration_messages"
    )
    op.drop_table("integration_messages")
    # ### end Alembic commands ###
