"""stokvel group tables, with row level security

``stokvels``, ``stokvel_members`` and ``stokvel_invitations`` (ticket R2-04).

Row level security, as for the ledger tables. ``app.current_user_id`` is who
is asking, ``app.is_admin_route`` is how:

- empty user id (workers, migrations) or admin route: every row
- customer route, reading. ``stokvels``: the Organiser, members (current or
  former) and pending invitees. ``stokvel_members``: your own row and your
  fellow members. ``stokvel_invitations``: your own, plus every invitation
  of a stokvel you are a member of or have a pending invitation to
- customer route, writing. ``stokvels``: the Organiser. ``stokvel_members``:
  your own row. ``stokvel_invitations``: the invitee or the Organiser

A policy that queries its own table, or two policies that query each other,
fail with "infinite recursion detected in policy". So the lookups live in
functions, which Postgres never inlines because of their ``SET`` clause.
Inside one, ``app.current_user_id`` is empty, the worker path, so its query
sees every row instead of calling the function again. Each policy is a
``CASE`` so that check runs before any function is called.

Revision ID: b2e338d2fc43
Revises: a8c3e1f42b90
Create Date: 2026-10-09 18:01:20.708076+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2e338d2fc43"
down_revision: str | None = "a8c3e1f42b90"
branch_labels: str | tuple | None = None
depends_on: str | tuple | None = None

_ME = "current_setting('app.current_user_id', true)"

# Membership counts former members too: they keep their history.
_FUNCTIONS = {
    "stokvel_is_member": "SELECT 1 FROM stokvel_members"
    " WHERE stokvel_id = p_stokvel_id AND user_id::text = p_user_id",
    "stokvel_is_organiser": "SELECT 1 FROM stokvels"
    " WHERE id = p_stokvel_id AND organiser_user_id::text = p_user_id",
    "stokvel_has_pending_invitation": "SELECT 1 FROM stokvel_invitations"
    " WHERE stokvel_id = p_stokvel_id AND invitee_user_id::text = p_user_id"
    " AND status = 'pending'",
}

# table: (customer may read, customer may write)
_POLICIES = {
    "stokvels": (
        f"organiser_user_id::text = {_ME}"
        f" OR stokvel_is_member(id, {_ME})"
        f" OR stokvel_has_pending_invitation(id, {_ME})",
        f"organiser_user_id::text = {_ME}",
    ),
    "stokvel_members": (
        f"user_id::text = {_ME} OR stokvel_is_member(stokvel_id, {_ME})",
        f"user_id::text = {_ME}",
    ),
    "stokvel_invitations": (
        f"invitee_user_id::text = {_ME}"
        f" OR stokvel_is_member(stokvel_id, {_ME})"
        f" OR stokvel_has_pending_invitation(stokvel_id, {_ME})",
        f"invitee_user_id::text = {_ME} OR stokvel_is_organiser(stokvel_id, {_ME})",
    ),
}


def _customer(expression: str) -> str:
    """Workers, migrations and admin routes see every row; customers see
    ``expression``."""
    return f"""CASE
      WHEN COALESCE({_ME}, '') = ''
        OR current_setting('app.is_admin_route', true) = 'true' THEN true
      ELSE ({expression})
    END"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stokvels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organiser_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column(
            "contribution_amount", sa.Numeric(precision=20, scale=8), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency IN ('ZAR', 'USD', 'ZWL', 'NAD')", name="stokvels_currency_valid"
        ),
        sa.CheckConstraint(
            "contribution_amount > 0", name="stokvels_contribution_amount_positive"
        ),
        sa.ForeignKeyConstraint(
            ["organiser_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stokvels_organiser_user_id"),
        "stokvels",
        ["organiser_user_id"],
        unique=False,
    )
    op.create_table(
        "stokvel_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stokvel_id", sa.Uuid(), nullable=False),
        sa.Column("invitee_user_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_changed_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(status = 'pending') = (status_changed_at IS NULL)",
            name="stokvel_invitations_changed_at_matches_status",
        ),
        sa.CheckConstraint(
            "status IN ('pending','accepted','declined','revoked','lapsed')",
            name="stokvel_invitations_status_valid",
        ),
        sa.CheckConstraint(
            "status NOT IN ('accepted','declined') OR status_changed_by_user_id = invitee_user_id",
            name="stokvel_invitations_invitee_answers",
        ),
        sa.CheckConstraint(
            "invitee_user_id <> invited_by_user_id", name="stokvel_invitations_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invitee_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_changed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stokvel_id"],
            ["stokvels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stokvel_invitations_invitee_user_id"),
        "stokvel_invitations",
        ["invitee_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stokvel_invitations_stokvel_id"),
        "stokvel_invitations",
        ["stokvel_id"],
        unique=False,
    )
    op.create_index(
        "uq_stokvel_invitations_pending",
        "stokvel_invitations",
        ["stokvel_id", "invitee_user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "stokvel_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stokvel_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("invitation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["stokvel_invitations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stokvel_id"],
            ["stokvels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invitation_id"),
    )
    op.create_index(
        op.f("ix_stokvel_members_stokvel_id"),
        "stokvel_members",
        ["stokvel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stokvel_members_user_id"), "stokvel_members", ["user_id"], unique=False
    )
    op.create_index(
        "uq_stokvel_members_active",
        "stokvel_members",
        ["stokvel_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("left_at IS NULL"),
        sqlite_where=sa.text("left_at IS NULL"),
    )
    # ### end Alembic commands ###

    for name, sql in _FUNCTIONS.items():
        op.execute(
            f"""
            CREATE FUNCTION {name}(p_stokvel_id uuid, p_user_id text)
              RETURNS boolean LANGUAGE sql STABLE
              SET app.current_user_id = ''
              AS $$ SELECT EXISTS ({sql}) $$
            """
        )
    for table, (using, check) in _POLICIES.items():
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_by_current_user ON {table}
              USING ({_customer(using)})
              WITH CHECK ({_customer(check)})
            """
        )


def downgrade() -> None:
    for table in _POLICIES:
        op.execute(f"DROP POLICY IF EXISTS {table}_by_current_user ON {table}")
    for name in _FUNCTIONS:
        op.execute(f"DROP FUNCTION IF EXISTS {name}(uuid, text)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_stokvel_members_active",
        table_name="stokvel_members",
        postgresql_where=sa.text("left_at IS NULL"),
        sqlite_where=sa.text("left_at IS NULL"),
    )
    op.drop_index(op.f("ix_stokvel_members_user_id"), table_name="stokvel_members")
    op.drop_index(op.f("ix_stokvel_members_stokvel_id"), table_name="stokvel_members")
    op.drop_table("stokvel_members")
    op.drop_index(
        "uq_stokvel_invitations_pending",
        table_name="stokvel_invitations",
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        op.f("ix_stokvel_invitations_stokvel_id"), table_name="stokvel_invitations"
    )
    op.drop_index(
        op.f("ix_stokvel_invitations_invitee_user_id"), table_name="stokvel_invitations"
    )
    op.drop_table("stokvel_invitations")
    op.drop_index(op.f("ix_stokvels_organiser_user_id"), table_name="stokvels")
    op.drop_table("stokvels")
    # ### end Alembic commands ###
