"""Every officially assigned ISO 3166-1 alpha-2 country, and the ones RemitX
operates in. What the countries migration inserts and what tests load; nothing
else reads this module.

The database is the authority once migrated. Opening a jurisdiction is an
UPDATE of `countries.operates_in` in a migration — plus, if applicants there
identify with a national number, a `kyc_identity_schemes` row — never an edit
to this tuple alone.

Names are English short names (CLDR, tidied where CLDR abbreviates).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CountrySeed:
    code: str
    name: str
    operates_in: bool = False


COUNTRY_SEEDS: tuple[CountrySeed, ...] = (
    CountrySeed("AD", "Andorra"),
    CountrySeed("AE", "United Arab Emirates"),
    CountrySeed("AF", "Afghanistan"),
    CountrySeed("AG", "Antigua and Barbuda"),
    CountrySeed("AI", "Anguilla"),
    CountrySeed("AL", "Albania"),
    CountrySeed("AM", "Armenia"),
    CountrySeed("AO", "Angola"),
    CountrySeed("AQ", "Antarctica"),
    CountrySeed("AR", "Argentina"),
    CountrySeed("AS", "American Samoa"),
    CountrySeed("AT", "Austria"),
    CountrySeed("AU", "Australia"),
    CountrySeed("AW", "Aruba"),
    CountrySeed("AX", "Åland Islands"),
    CountrySeed("AZ", "Azerbaijan"),
    CountrySeed("BA", "Bosnia and Herzegovina"),
    CountrySeed("BB", "Barbados"),
    CountrySeed("BD", "Bangladesh"),
    CountrySeed("BE", "Belgium"),
    CountrySeed("BF", "Burkina Faso"),
    CountrySeed("BG", "Bulgaria"),
    CountrySeed("BH", "Bahrain"),
    CountrySeed("BI", "Burundi"),
    CountrySeed("BJ", "Benin"),
    CountrySeed("BL", "Saint Barthélemy"),
    CountrySeed("BM", "Bermuda"),
    CountrySeed("BN", "Brunei"),
    CountrySeed("BO", "Bolivia"),
    CountrySeed("BQ", "Bonaire, Sint Eustatius and Saba"),
    CountrySeed("BR", "Brazil"),
    CountrySeed("BS", "Bahamas"),
    CountrySeed("BT", "Bhutan"),
    CountrySeed("BV", "Bouvet Island"),
    CountrySeed("BW", "Botswana"),
    CountrySeed("BY", "Belarus"),
    CountrySeed("BZ", "Belize"),
    CountrySeed("CA", "Canada"),
    CountrySeed("CC", "Cocos (Keeling) Islands"),
    CountrySeed("CD", "Democratic Republic of the Congo"),
    CountrySeed("CF", "Central African Republic"),
    CountrySeed("CG", "Republic of the Congo"),
    CountrySeed("CH", "Switzerland"),
    CountrySeed("CI", "Côte d'Ivoire"),
    CountrySeed("CK", "Cook Islands"),
    CountrySeed("CL", "Chile"),
    CountrySeed("CM", "Cameroon"),
    CountrySeed("CN", "China"),
    CountrySeed("CO", "Colombia"),
    CountrySeed("CR", "Costa Rica"),
    CountrySeed("CU", "Cuba"),
    CountrySeed("CV", "Cape Verde"),
    CountrySeed("CW", "Curaçao"),
    CountrySeed("CX", "Christmas Island"),
    CountrySeed("CY", "Cyprus"),
    CountrySeed("CZ", "Czechia"),
    CountrySeed("DE", "Germany"),
    CountrySeed("DJ", "Djibouti"),
    CountrySeed("DK", "Denmark"),
    CountrySeed("DM", "Dominica"),
    CountrySeed("DO", "Dominican Republic"),
    CountrySeed("DZ", "Algeria"),
    CountrySeed("EC", "Ecuador"),
    CountrySeed("EE", "Estonia"),
    CountrySeed("EG", "Egypt"),
    CountrySeed("EH", "Western Sahara"),
    CountrySeed("ER", "Eritrea"),
    CountrySeed("ES", "Spain"),
    CountrySeed("ET", "Ethiopia"),
    CountrySeed("FI", "Finland"),
    CountrySeed("FJ", "Fiji"),
    CountrySeed("FK", "Falkland Islands"),
    CountrySeed("FM", "Micronesia"),
    CountrySeed("FO", "Faroe Islands"),
    CountrySeed("FR", "France"),
    CountrySeed("GA", "Gabon"),
    CountrySeed("GB", "United Kingdom"),
    CountrySeed("GD", "Grenada"),
    CountrySeed("GE", "Georgia"),
    CountrySeed("GF", "French Guiana"),
    CountrySeed("GG", "Guernsey"),
    CountrySeed("GH", "Ghana"),
    CountrySeed("GI", "Gibraltar"),
    CountrySeed("GL", "Greenland"),
    CountrySeed("GM", "Gambia"),
    CountrySeed("GN", "Guinea"),
    CountrySeed("GP", "Guadeloupe"),
    CountrySeed("GQ", "Equatorial Guinea"),
    CountrySeed("GR", "Greece"),
    CountrySeed("GS", "South Georgia and South Sandwich Islands"),
    CountrySeed("GT", "Guatemala"),
    CountrySeed("GU", "Guam"),
    CountrySeed("GW", "Guinea-Bissau"),
    CountrySeed("GY", "Guyana"),
    CountrySeed("HK", "Hong Kong"),
    CountrySeed("HM", "Heard and McDonald Islands"),
    CountrySeed("HN", "Honduras"),
    CountrySeed("HR", "Croatia"),
    CountrySeed("HT", "Haiti"),
    CountrySeed("HU", "Hungary"),
    CountrySeed("ID", "Indonesia"),
    CountrySeed("IE", "Ireland"),
    CountrySeed("IL", "Israel"),
    CountrySeed("IM", "Isle of Man"),
    CountrySeed("IN", "India"),
    CountrySeed("IO", "British Indian Ocean Territory"),
    CountrySeed("IQ", "Iraq"),
    CountrySeed("IR", "Iran"),
    CountrySeed("IS", "Iceland"),
    CountrySeed("IT", "Italy"),
    CountrySeed("JE", "Jersey"),
    CountrySeed("JM", "Jamaica"),
    CountrySeed("JO", "Jordan"),
    CountrySeed("JP", "Japan"),
    CountrySeed("KE", "Kenya"),
    CountrySeed("KG", "Kyrgyzstan"),
    CountrySeed("KH", "Cambodia"),
    CountrySeed("KI", "Kiribati"),
    CountrySeed("KM", "Comoros"),
    CountrySeed("KN", "Saint Kitts and Nevis"),
    CountrySeed("KP", "North Korea"),
    CountrySeed("KR", "South Korea"),
    CountrySeed("KW", "Kuwait"),
    CountrySeed("KY", "Cayman Islands"),
    CountrySeed("KZ", "Kazakhstan"),
    CountrySeed("LA", "Laos"),
    CountrySeed("LB", "Lebanon"),
    CountrySeed("LC", "Saint Lucia"),
    CountrySeed("LI", "Liechtenstein"),
    CountrySeed("LK", "Sri Lanka"),
    CountrySeed("LR", "Liberia"),
    CountrySeed("LS", "Lesotho"),
    CountrySeed("LT", "Lithuania"),
    CountrySeed("LU", "Luxembourg"),
    CountrySeed("LV", "Latvia"),
    CountrySeed("LY", "Libya"),
    CountrySeed("MA", "Morocco"),
    CountrySeed("MC", "Monaco"),
    CountrySeed("MD", "Moldova"),
    CountrySeed("ME", "Montenegro"),
    CountrySeed("MF", "Saint Martin"),
    CountrySeed("MG", "Madagascar"),
    CountrySeed("MH", "Marshall Islands"),
    CountrySeed("MK", "North Macedonia"),
    CountrySeed("ML", "Mali"),
    CountrySeed("MM", "Myanmar"),
    CountrySeed("MN", "Mongolia"),
    CountrySeed("MO", "Macao"),
    CountrySeed("MP", "Northern Mariana Islands"),
    CountrySeed("MQ", "Martinique"),
    CountrySeed("MR", "Mauritania"),
    CountrySeed("MS", "Montserrat"),
    CountrySeed("MT", "Malta"),
    CountrySeed("MU", "Mauritius"),
    CountrySeed("MV", "Maldives"),
    CountrySeed("MW", "Malawi"),
    CountrySeed("MX", "Mexico"),
    CountrySeed("MY", "Malaysia"),
    CountrySeed("MZ", "Mozambique"),
    CountrySeed("NA", "Namibia"),
    CountrySeed("NC", "New Caledonia"),
    CountrySeed("NE", "Niger"),
    CountrySeed("NF", "Norfolk Island"),
    CountrySeed("NG", "Nigeria"),
    CountrySeed("NI", "Nicaragua"),
    CountrySeed("NL", "Netherlands"),
    CountrySeed("NO", "Norway"),
    CountrySeed("NP", "Nepal"),
    CountrySeed("NR", "Nauru"),
    CountrySeed("NU", "Niue"),
    CountrySeed("NZ", "New Zealand"),
    CountrySeed("OM", "Oman"),
    CountrySeed("PA", "Panama"),
    CountrySeed("PE", "Peru"),
    CountrySeed("PF", "French Polynesia"),
    CountrySeed("PG", "Papua New Guinea"),
    CountrySeed("PH", "Philippines"),
    CountrySeed("PK", "Pakistan"),
    CountrySeed("PL", "Poland"),
    CountrySeed("PM", "Saint Pierre and Miquelon"),
    CountrySeed("PN", "Pitcairn Islands"),
    CountrySeed("PR", "Puerto Rico"),
    CountrySeed("PS", "Palestine"),
    CountrySeed("PT", "Portugal"),
    CountrySeed("PW", "Palau"),
    CountrySeed("PY", "Paraguay"),
    CountrySeed("QA", "Qatar"),
    CountrySeed("RE", "Réunion"),
    CountrySeed("RO", "Romania"),
    CountrySeed("RS", "Serbia"),
    CountrySeed("RU", "Russia"),
    CountrySeed("RW", "Rwanda"),
    CountrySeed("SA", "Saudi Arabia"),
    CountrySeed("SB", "Solomon Islands"),
    CountrySeed("SC", "Seychelles"),
    CountrySeed("SD", "Sudan"),
    CountrySeed("SE", "Sweden"),
    CountrySeed("SG", "Singapore"),
    CountrySeed("SH", "Saint Helena"),
    CountrySeed("SI", "Slovenia"),
    CountrySeed("SJ", "Svalbard and Jan Mayen"),
    CountrySeed("SK", "Slovakia"),
    CountrySeed("SL", "Sierra Leone"),
    CountrySeed("SM", "San Marino"),
    CountrySeed("SN", "Senegal"),
    CountrySeed("SO", "Somalia"),
    CountrySeed("SR", "Suriname"),
    CountrySeed("SS", "South Sudan"),
    CountrySeed("ST", "São Tomé and Príncipe"),
    CountrySeed("SV", "El Salvador"),
    CountrySeed("SX", "Sint Maarten"),
    CountrySeed("SY", "Syria"),
    CountrySeed("SZ", "Eswatini"),
    CountrySeed("TC", "Turks and Caicos Islands"),
    CountrySeed("TD", "Chad"),
    CountrySeed("TF", "French Southern Territories"),
    CountrySeed("TG", "Togo"),
    CountrySeed("TH", "Thailand"),
    CountrySeed("TJ", "Tajikistan"),
    CountrySeed("TK", "Tokelau"),
    CountrySeed("TL", "Timor-Leste"),
    CountrySeed("TM", "Turkmenistan"),
    CountrySeed("TN", "Tunisia"),
    CountrySeed("TO", "Tonga"),
    CountrySeed("TR", "Türkiye"),
    CountrySeed("TT", "Trinidad and Tobago"),
    CountrySeed("TV", "Tuvalu"),
    CountrySeed("TW", "Taiwan"),
    CountrySeed("TZ", "Tanzania"),
    CountrySeed("UA", "Ukraine"),
    CountrySeed("UG", "Uganda"),
    CountrySeed("UM", "United States Minor Outlying Islands"),
    CountrySeed("US", "United States", operates_in=True),
    CountrySeed("UY", "Uruguay"),
    CountrySeed("UZ", "Uzbekistan"),
    CountrySeed("VA", "Vatican City"),
    CountrySeed("VC", "Saint Vincent and the Grenadines"),
    CountrySeed("VE", "Venezuela"),
    CountrySeed("VG", "British Virgin Islands"),
    CountrySeed("VI", "United States Virgin Islands"),
    CountrySeed("VN", "Vietnam"),
    CountrySeed("VU", "Vanuatu"),
    CountrySeed("WF", "Wallis and Futuna"),
    CountrySeed("WS", "Samoa"),
    CountrySeed("YE", "Yemen"),
    CountrySeed("YT", "Mayotte"),
    CountrySeed("ZA", "South Africa", operates_in=True),
    CountrySeed("ZM", "Zambia"),
    CountrySeed("ZW", "Zimbabwe"),
)

if len({seed.code for seed in COUNTRY_SEEDS}) != len(COUNTRY_SEEDS):
    raise RuntimeError("COUNTRY_SEEDS must list each ISO 3166-1 code once")
