"""Integration smoke-test message.

THROWAWAY: backs the manual end-to-end test at /integration-test and carries no
domain meaning. Removed once real remittance flows land.

This model is the source of truth: the table is created by an Alembic
migration autogenerated from it. `create_all()` only ever runs against
throwaway SQLite under test.
"""

import uuid
from datetime import UTC, datetime

from sqlalchemy import CheckConstraint, DateTime, Index, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from remitx_api.extensions import Base

BODY_MAX_LENGTH = 280

STATUS_PENDING = "PENDING"
STATUS_PROCESSED = "PROCESSED"


def utcnow() -> datetime:
    return datetime.now(UTC)


class IntegrationMessage(Base):
    __tablename__ = "integration_messages"
    __table_args__ = (
        CheckConstraint(
            f"length(body) BETWEEN 1 AND {BODY_MAX_LENGTH}",
            name="integration_messages_body_length",
        ),
        CheckConstraint(
            f"status IN ('{STATUS_PENDING}', '{STATUS_PROCESSED}')",
            name="integration_messages_status_valid",
        ),
        Index("idx_integration_messages_created_at", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
    )
    body: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        default=STATUS_PENDING,
    )
    # Set in Python rather than by the database: SQLite's CURRENT_TIMESTAMP has
    # only second precision, which is too coarse to order rapid inserts.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
    )
    processed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
