Table "alembic_version" {
  "version_num" varchar(32) [pk, not null]
}

Table "users" {
  "id" uuid [pk, not null]
  "email" text [unique, not null]
}

Table "orders" {
  "id" uuid [pk, not null]
  "user_id" uuid [not null]
  "total" numeric(12,2) [not null, check: `total >= (0)::numeric`]
  "created_at" timestamptz [not null, default: `now()`]

  Indexes {
    user_id [type: btree, name: "ix_orders_user_id"]
  }
}

Table "payments" {
  "id" uuid [pk, not null]
  "order_id" uuid [unique, not null]
  "amount" numeric(12,2) [not null]
  "status" text [not null, default: 'pending']

  Checks {
    `amount > (0)::numeric` [name: 'payments_amount_positive']
  }
}

Ref "orders_user_id_fkey":"users"."id" < "orders"."user_id" [delete: cascade]

Ref "payments_order_id_fkey":"orders"."id" - "payments"."order_id"
