"""The OpenAPI contract, and the export the frontend client is generated from.

The TypeScript client in ``frontend/app/client`` is generated by Hey API from
``frontend/openapi.json``, which is this module's output. Everything a client
author would otherwise have to guess — function names, grouping, which calls
need a session, what an error looks like — is declared here or on the routes::

    python scripts/export_openapi.py            # rewrite frontend/openapi.json
    python scripts/export_openapi.py --check    # exit 1 if it is stale

``tests/test_openapi.py`` runs the check, so CI and the pre-commit hook fail on
an API change whose spec was not regenerated.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.routing import APIRoute
from fastapi.security import HTTPBearer

from remitx_api.models.schemas.base import Schema

SPEC_PATH = Path(__file__).resolve().parent.parent.parent / "frontend" / "openapi.json"

TITLE = "RemitX API"
VERSION = "0.1.0"
DESCRIPTION = (
    "ZAR to RLUSD remittance on the XRP Ledger Testnet. Authenticated routes "
    "take a Clerk session token as a bearer token."
)


class Tag:
    """Tag names. Dotted: the generated client nests operations by segment, so
    ``admin.users`` becomes ``api.admin.users``. Segments must be identifiers.
    """

    SYSTEM = "system"
    ME = "me"
    INTEGRATION = "integration"
    BENEFICIARIES = "beneficiaries"
    QUOTES = "quotes"
    REMITTANCES = "remittances"
    DASHBOARD = "dashboard"
    ACCOUNTS = "accounts"
    BANK_ACCOUNTS = "bank_accounts"
    WITHDRAWALS = "withdrawals"
    KYC_ONBOARDING = "kyc.onboarding"
    KYC_DOCUMENTS = "kyc.documents"
    ADMIN_ROLES = "admin.roles"
    ADMIN_USERS = "admin.users"
    ADMIN_ACCOUNTS = "admin.accounts"
    ADMIN_OPERATIONS = "admin.operations"
    ADMIN_DEPOSITS = "admin.deposits"
    ADMIN_BANK_ACCOUNTS = "admin.bank_accounts"
    ADMIN_WITHDRAWALS = "admin.withdrawals"
    ADMIN_KYC_APPLICATIONS = "admin.kyc.applications"
    ADMIN_KYC_DOCUMENTS = "admin.kyc.documents"
    ADMIN_AUDIT = "admin.audit"


TAGS: list[dict[str, str]] = [
    {"name": Tag.SYSTEM, "description": "Liveness probe. No session required."},
    {"name": Tag.ME, "description": "The signed-in caller's own profile and access."},
    {
        "name": Tag.INTEGRATION,
        "description": "Round-trip test messages through the settlement queue.",
    },
    {
        "name": Tag.BENEFICIARIES,
        "description": "A sender's contacts they can quote or remit to.",
    },
    {
        "name": Tag.QUOTES,
        "description": "Priced, time-boxed remittance offers.",
    },
    {
        "name": Tag.REMITTANCES,
        "description": "Confirming a quote, then following the transfer as it settles.",
    },
    {
        "name": Tag.DASHBOARD,
        "description": "The signed-in customer's account overview.",
    },
    {
        "name": Tag.ACCOUNTS,
        "description": "A caller's own currency account balances and history.",
    },
    {
        "name": Tag.BANK_ACCOUNTS,
        "description": "A caller's own external bank accounts for withdrawals.",
    },
    {
        "name": Tag.WITHDRAWALS,
        "description": "Requesting a withdrawal from a fiat account to a bank account.",
    },
    {
        "name": Tag.KYC_ONBOARDING,
        "description": "The applicant's resumable KYC application.",
    },
    {
        "name": Tag.KYC_DOCUMENTS,
        "description": "The applicant's own KYC evidence uploads.",
    },
    {"name": Tag.ADMIN_ROLES, "description": "The role catalogue."},
    {
        "name": Tag.ADMIN_USERS,
        "description": "Who holds which staff role, and granting and revoking them.",
    },
    {
        "name": Tag.ADMIN_ACCOUNTS,
        "description": "RemitX's own platform account balances.",
    },
    {
        "name": Tag.ADMIN_OPERATIONS,
        "description": "Settlement volume and the transfer pipeline.",
    },
    {
        "name": Tag.ADMIN_DEPOSITS,
        "description": "ZAR cash-in reconciliation against bank statements.",
    },
    {
        "name": Tag.ADMIN_BANK_ACCOUNTS,
        "description": "Verifying or rejecting a customer's external bank account.",
    },
    {
        "name": Tag.ADMIN_WITHDRAWALS,
        "description": "Read-only withdrawal history; withdrawals settle on request.",
    },
    {
        "name": Tag.ADMIN_KYC_APPLICATIONS,
        "description": "The reviewer queue and risk ratings.",
    },
    {
        "name": Tag.ADMIN_KYC_DOCUMENTS,
        "description": "Audited reviewer access to KYC evidence.",
    },
    {
        "name": Tag.ADMIN_AUDIT,
        "description": (
            "Privileged actions and sensitive reads — who did what, to whom, and when."
        ),
    },
]


# Declared on every authenticated router. ``auto_error=False`` because this
# only documents the scheme — ``get_current_user`` is what verifies the token,
# and it keeps answering 401 itself. Hey API reads the resulting ``security``
# entry to decide which calls get the ``Authorization`` header.
bearer_scheme = HTTPBearer(
    auto_error=False,
    scheme_name="ClerkSession",
    description="A Clerk session token.",
)


class ErrorResponse(Schema):
    """Every refusal that is not a validation failure: ``HTTPException`` and
    ``DomainError`` both answer in this shape."""

    detail: str


def error_responses(*status_codes: int) -> dict[int | str, dict[str, Any]]:
    """``responses=`` entries for refusals a route (or router) can answer."""
    descriptions = {
        400: "The request was refused.",
        401: "No valid session.",
        403: "The caller lacks the required permission.",
        404: "Not found.",
        409: "The current state refuses the request.",
        413: "The upload is too large.",
        422: "The request body failed validation.",
        502: "Object storage failed.",
        503: "A service the request depends on is unavailable.",
    }
    return {
        code: {"model": ErrorResponse, "description": descriptions[code]}
        for code in status_codes
    }


def operation_id(route: APIRoute) -> str:
    """The handler's own name, so ``list_roles`` becomes ``listRoles`` in the
    client rather than ``listRolesAdminRolesGet``. Handler names are therefore
    unique across the API; ``tests/test_openapi.py`` holds them to it."""
    return route.name


def render(app: FastAPI) -> str:
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if stale")
    parser.add_argument("--output", type=Path, default=SPEC_PATH)
    args = parser.parse_args(argv)

    # Imported here: ``remitx_api`` imports the app eagerly, and the app
    # imports this module for the tag names.
    from remitx_api.app import create_app
    from remitx_api.config import TestConfig

    spec = render(create_app(TestConfig))
    current = args.output.read_text() if args.output.exists() else ""

    if args.check:
        if current != spec:
            print(
                f"{args.output} is stale. "
                "Run: cd api && python scripts/export_openapi.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if current != spec:
        args.output.write_text(spec)
        print(f"wrote {args.output}")
    return 0
