"""The OpenAPI contract, and the export the frontend client is generated from.

The TypeScript client in ``frontend/app/client`` is generated by Hey API from
``frontend/openapi.json``, which is this module's output. Everything a client
author would otherwise have to guess — function names, grouping, which calls
need a session, what an error looks like — is declared here or on the routes::

    python scripts/export_openapi.py            # rewrite frontend/openapi.json
    python scripts/export_openapi.py --check    # exit 1 if it is stale

``tests/test_openapi.py`` runs the check, so CI and the pre-commit hook fail on
an API change whose spec was not regenerated.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.routing import APIRoute
from fastapi.security import HTTPBearer

from remitx_api.models.schemas.base import Schema

SPEC_PATH = Path(__file__).resolve().parent.parent.parent / "frontend" / "openapi.json"

TITLE = "RemitX API"
VERSION = "0.1.0"
DESCRIPTION = (
    "ZAR to RLUSD remittance on the XRP Ledger Testnet. Authenticated routes "
    "take a Clerk session token as a bearer token."
)


class Tag:
    """Tag names. Dotted: the generated client nests operations by segment, so
    ``admin.users`` becomes ``api.admin.users``. Segments must be identifiers.
    """

    SYSTEM = "system"
    ME = "me"
    INTEGRATION = "integration"
    BENEFICIARIES = "beneficiaries"
    QUOTES = "quotes"
    REMITTANCES = "remittances"
    ACCOUNTS = "accounts"
    KYC_ONBOARDING = "kyc.onboarding"
    KYC_DOCUMENTS = "kyc.documents"
    ADMIN_ROLES = "admin.roles"
    ADMIN_USERS = "admin.users"
    ADMIN_DEPOSITS = "admin.deposits"
    ADMIN_KYC_APPLICATIONS = "admin.kyc.applications"
    ADMIN_KYC_DOCUMENTS = "admin.kyc.documents"


TAGS: list[dict[str, str]] = [
    {"name": Tag.SYSTEM, "description": "Liveness probe. No session required."},
    {"name": Tag.ME, "description": "The signed-in caller's own profile and access."},
    {
        "name": Tag.INTEGRATION,
        "description": "Round-trip test messages through the settlement queue.",
    },
    {
        "name": Tag.BENEFICIARIES,
        "description": "A sender's contacts they can quote or remit to.",
    },
    {
        "name": Tag.QUOTES,
        "description": "Priced, time-boxed remittance offers.",
    },
    {
        "name": Tag.REMITTANCES,
        "description": "Confirming a quote and starting settlement.",
    },
    {
        "name": Tag.ACCOUNTS,
        "description": "A caller's own currency account balances and history.",
    },
    {
        "name": Tag.KYC_ONBOARDING,
        "description": "The applicant's resumable KYC application.",
    },
    {
        "name": Tag.KYC_DOCUMENTS,
        "description": "The applicant's own KYC evidence uploads.",
    },
    {"name": Tag.ADMIN_ROLES, "description": "The role catalogue."},
    {
        "name": Tag.ADMIN_USERS,
        "description": "Who holds which staff role, and granting and revoking them.",
    },
    {
        "name": Tag.ADMIN_DEPOSITS,
        "description": "ZAR cash-in reconciliation against bank statements.",
    },
    {
        "name": Tag.ADMIN_KYC_APPLICATIONS,
        "description": "The reviewer queue and risk ratings.",
    },
    {
        "name": Tag.ADMIN_KYC_DOCUMENTS,
        "description": "Audited reviewer access to KYC evidence.",
    },
]


# Declared on every authenticated router. ``auto_error=False`` because this
# only documents the scheme — ``get_current_user`` is what verifies the token,
# and it keeps answering 401 itself. Hey API reads the resulting ``security``
# entry to decide which calls get the ``Authorization`` header.
bearer_scheme = HTTPBearer(
    auto_error=False,
    scheme_name="ClerkSession",
    description="A Clerk session token.",
)


class ErrorResponse(Schema):
    """Every refusal that is not a validation failure: ``HTTPException`` and
    ``DomainError`` both answer in this shape."""

    detail: str


def error_responses(*status_codes: int) -> dict[int | str, dict[str, Any]]:
    """``responses=`` entries for refusals a route (or router) can answer."""
    descriptions = {
        400: "The request was refused.",
        401: "No valid session.",
        403: "The caller lacks the required permission.",
        404: "Not found.",
        409: "The current state refuses the request.",
        413: "The upload is too large.",
        502: "Object storage failed.",
        503: "Object storage is not configured.",
    }
    return {
        code: {"model": ErrorResponse, "description": descriptions[code]}
        for code in status_codes
    }


def operation_id(route: APIRoute) -> str:
    """The handler's own name, so ``list_roles`` becomes ``listRoles`` in the
    client rather than ``listRolesAdminRolesGet``. Handler names are therefore
    unique across the API; ``tests/test_openapi.py`` holds them to it."""
    return route.name


def render(app: FastAPI) -> str:
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if stale")
    parser.add_argument("--output", type=Path, default=SPEC_PATH)
    args = parser.parse_args(argv)

    # Imported here: ``remitx_api`` imports the app eagerly, and the app
    # imports this module for the tag names.
    from remitx_api.app import create_app
    from remitx_api.config import TestConfig

    spec = render(create_app(TestConfig))
    current = args.output.read_text() if args.output.exists() else ""

    if args.check:
        if current != spec:
            print(
                f"{args.output} is stale. "
                "Run: cd api && python scripts/export_openapi.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if current != spec:
        args.output.write_text(spec)
        print(f"wrote {args.output}")
    return 0
