"""Turn a load-test results folder into summary + canvas + HTML report.

Writes summary.json, report.canvas.tsx, and performance-report.html.

python to_canvas.py tools/loadtest/results/<timestamp>
make loadtest-canvas RESULTS=tools/loadtest/results/<timestamp>
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from loadtest_summary import RunSummary, build_summary, summary_to_dict

HERE = Path(__file__).resolve().parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "run_dir",
        type=Path,
        help="Results folder (contains profile.json and compute/*/stats)",
    )
    args = parser.parse_args(argv)
    run_dir = args.run_dir.resolve()
    if not run_dir.is_dir():
        print(f"to_canvas: not a directory: {run_dir}", file=sys.stderr)
        return 1
    try:
        summary = build_summary(run_dir)
    except (FileNotFoundError, ValueError, json.JSONDecodeError, KeyError) as exc:
        print(f"to_canvas: {exc}", file=sys.stderr)
        return 1

    summary_path = run_dir / "summary.json"
    summary_path.write_text(json.dumps(summary_to_dict(summary), indent=2) + "\n")
    canvas_path = run_dir / "report.canvas.tsx"
    canvas_path.write_text(render_canvas(summary))
    html_path = run_dir / "performance-report.html"
    html_path.write_text(render_html(summary))
    print(f"Wrote {summary_path}")
    print(f"Wrote {canvas_path}")
    print(f"Wrote {html_path}")
    return 0


def _report_payload(summary: RunSummary) -> dict:
    user_cats = _user_categories(summary)
    return {
        "userCats": [str(u) for u in user_cats],
        "latencySeries": _latency_series(summary, user_cats),
        "rpsSeries": _rps_series(summary, user_cats),
        "headline": _headline_stats(summary),
        "settleRows": _settle_table_rows(summary),
        "endpointRows": _endpoint_table_rows(summary),
        "bottleneck": summary.bottleneck,
        "profileName": summary.profile_name,
        "description": summary.description,
        "burnP50": summary.burn_p50_s,
        "burnP95": summary.burn_p95_s,
        "computeLabels": ", ".join(
            f"{c.name} (API {c.api_cpus} / worker {c.worker_cpus} / "
            f"pg {c.postgres_cpus} CPU)"
            for c in summary.compute
        ),
        "locustSteps": summary.locust_steps,
    }


def render_canvas(summary: RunSummary) -> str:
    """Emit a Cursor canvas module covering the project-brief performance bullets."""
    data_json = json.dumps(_report_payload(summary), indent=2)

    return f"""import {{
  BarChart,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  LineChart,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text,
}} from "cursor/canvas";

/** Generated by tools/loadtest/to_canvas.py — do not edit by hand. */
const data = {data_json} as const;

export default function LoadtestPerformanceReport() {{
  const latencySeries = data.latencySeries.map((s) => ({{
    name: s.name,
    data: s.data.map((v) => (v == null ? 0 : v)),
    tone: s.tone as "danger" | "success" | "info" | "warning" | undefined,
  }}));
  const rpsSeries = data.rpsSeries.map((s) => ({{
    name: s.name,
    data: s.data.map((v) => (v == null ? 0 : v)),
    tone: s.tone as "danger" | "success" | "info" | "warning" | undefined,
  }}));

  return (
    <Stack gap={{28}}>
      <Stack gap={{8}}>
        <H1>Performance testing results</H1>
        <Text tone="secondary">
          Profile {{data.profileName}}. {{data.description}} Compute:{{" "}}
          {{data.computeLabels}}. Locust user steps:{{" "}}
          {{data.locustSteps.join(" → ")}}.
        </Text>
        <Row gap={{8}} wrap>
          <Pill tone="info">HTTP vs SETTLE split</Pill>
          <Pill tone="neutral">
            RLUSD burn p50 {{data.burnP50}} s / p95 {{data.burnP95}} s
          </Pill>
        </Row>
      </Stack>

      <Callout tone="warning">{{data.bottleneck}}</Callout>

      <Grid columns={{4}} gap={{12}}>
        <Stat
          value={{data.headline.worstHttpMedian}}
          label="Worst HTTP median @ 10 users"
          tone="danger"
        />
        <Stat
          value={{data.headline.bestHttpMedian}}
          label="Best HTTP median @ 10 users"
          tone="success"
        />
        <Stat value={{data.headline.peakHttpRps}} label="Peak HTTP requests/s" />
        <Stat
          value={{data.headline.peakSettleRps}}
          label="Peak settle throughput (end-to-end /s)"
        />
      </Grid>

      <Divider />

      <Stack gap={{12}}>
        <H2>API response times under concurrent use</H2>
        <Text>
          HTTP-only median latency (SETTLE events excluded) as Locust ramps
          concurrent users. One series per compute config.
        </Text>
        <LineChart
          categories={{[...data.userCats]}}
          series={{latencySeries}}
          height={{280}}
        />
      </Stack>

      <Stack gap={{12}}>
        <H2>Requests processed per second</H2>
        <Text>
          HTTP request rate (SETTLE excluded) at each user-step plateau.
        </Text>
        <BarChart
          categories={{[...data.userCats]}}
          series={{rpsSeries}}
          height={{260}}
        />
      </Stack>

      <Divider />

      <Stack gap={{12}}>
        <H2>Settlement: queue throughput, RLUSD time, success rates</H2>
        <Text>
          Message-queue throughput is the Locust SETTLE “end to end” rate
          (settlements per second). RLUSD processing time uses the profile’s
          calibrated Testnet burn (from qa_xrpl_timings.sql) plus in-run
          “chain + confirm” medians under load.
        </Text>
        <Grid columns={{3}} gap={{12}}>
          <Stat
            value={{`${{data.burnP50}} s`}}
            label="Calibrated RLUSD burn p50 (Testnet)"
          />
          <Stat
            value={{`${{data.burnP95}} s`}}
            label="Calibrated RLUSD burn p95 (Testnet)"
          />
          <Stat
            value={{data.headline.httpFailPct}}
            label="HTTP failure rate (all compute)"
            tone={{data.headline.httpFailTone as "danger" | "success" | undefined}}
          />
        </Grid>
        <Table
          headers={{[
            "Compute",
            "Settle /s @ peak users",
            "Chain+confirm median",
            "HTTP fail %",
            "Settle fail %",
          ]}}
          columnAlign={{["left", "right", "right", "right", "right"]}}
          rows={{data.settleRows.map((r) => [...r])}}
        />
      </Stack>

      {{data.endpointRows.length > 0 ? (
        <Card>
          <CardHeader>Slowest HTTP endpoints @ 10 users (baseline compute)</CardHeader>
          <CardBody>
            <Table
              headers={{["Endpoint", "Median (ms)", "Requests", "Failures"]}}
              columnAlign={{["left", "right", "right", "right"]}}
              rows={{data.endpointRows.map((r) => [...r])}}
            />
          </CardBody>
        </Card>
      ) : null}}
    </Stack>
  );
}}
"""


def render_html(summary: RunSummary) -> str:
    """Self-contained HTML twin of the canvas (no CDN; SVG charts)."""
    data = _report_payload(summary)
    data_json = json.dumps(data)
    # Escape </script> in JSON for HTML embedding.
    data_json = data_json.replace("<", "\\u003c")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Performance testing results — { _esc(summary.profile_name) }</title>
<style>
  :root {{
    --bg: #f7f7f5;
    --fg: #1a1a1a;
    --muted: #5c5c5c;
    --card: #fff;
    --border: #e2e2de;
    --danger: #b42318;
    --success: #027a48;
    --info: #175cd3;
    --warning: #b54708;
    --warning-bg: #fffaeb;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg: #141414;
      --fg: #f2f2f0;
      --muted: #a3a3a0;
      --card: #1e1e1c;
      --border: #333330;
      --danger: #f97066;
      --success: #6ce9a6;
      --info: #84caff;
      --warning: #fec84b;
      --warning-bg: #2a2110;
    }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    font: 15px/1.5 system-ui, -apple-system, sans-serif;
    color: var(--fg);
    background: var(--bg);
  }}
  main {{ max-width: 960px; margin: 0 auto; padding: 32px 20px 64px; }}
  h1 {{ font-size: 1.75rem; font-weight: 600; margin: 0 0 8px; }}
  h2 {{ font-size: 1.15rem; font-weight: 600; margin: 0 0 8px; }}
  p.muted {{ color: var(--muted); margin: 0 0 16px; }}
  .pills {{ display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 20px; }}
  .pill {{
    font-size: 12px; padding: 4px 10px; border-radius: 999px;
    border: 1px solid var(--border); background: var(--card);
  }}
  .callout {{
    background: var(--warning-bg); border: 1px solid var(--warning);
    border-radius: 8px; padding: 14px 16px; margin-bottom: 24px;
  }}
  .stats {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 12px; margin-bottom: 28px;
  }}
  .stat {{
    background: var(--card); border: 1px solid var(--border);
    border-radius: 8px; padding: 14px 16px;
  }}
  .stat .v {{ font-size: 1.35rem; font-weight: 600; }}
  .stat .l {{ font-size: 12px; color: var(--muted); margin-top: 4px; }}
  .stat.danger .v {{ color: var(--danger); }}
  .stat.success .v {{ color: var(--success); }}
  section {{ margin-bottom: 32px; }}
  .chart {{
    background: var(--card); border: 1px solid var(--border);
    border-radius: 8px; padding: 16px; margin-top: 12px;
  }}
  svg {{ width: 100%; height: auto; display: block; }}
  table {{
    width: 100%; border-collapse: collapse; background: var(--card);
    border: 1px solid var(--border); border-radius: 8px; overflow: hidden;
    margin-top: 12px;
  }}
  th, td {{
    text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--border);
    font-size: 14px;
  }}
  th {{ font-weight: 600; color: var(--muted); font-size: 12px; }}
  td.num, th.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  tr:last-child td {{ border-bottom: none; }}
  .legend {{
    display: flex; flex-wrap: wrap; gap: 12px 18px; margin-top: 10px;
    font-size: 12px; color: var(--muted);
  }}
  .legend i {{
    display: inline-block; width: 10px; height: 10px; border-radius: 2px;
    margin-right: 6px;
  }}
  footer {{ color: var(--muted); font-size: 12px; margin-top: 40px; }}
</style>
</head>
<body>
<main id="app"></main>
<script type="application/json" id="report-data">{data_json}</script>
<script>
const data = JSON.parse(document.getElementById("report-data").textContent);
const tones = {{ danger: "var(--danger)", success: "var(--success)", info: "var(--info)", warning: "var(--warning)" }};

function esc(s) {{
  return String(s).replace(/[&<>"']/g, c => ({{"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;","'":"&#39;"}}[c]));
}}

function lineChart(series, cats, height) {{
  const W = 880, H = height, pad = {{ t: 16, r: 16, b: 36, l: 56 }};
  const vals = series.flatMap(s => s.data.filter(v => v != null));
  const maxY = Math.max(...vals, 1) * 1.08;
  const innerW = W - pad.l - pad.r, innerH = H - pad.t - pad.b;
  const x = i => pad.l + (cats.length <= 1 ? innerW/2 : i * innerW / (cats.length - 1));
  const y = v => pad.t + innerH - (v / maxY) * innerH;
  const grid = [0, 0.25, 0.5, 0.75, 1].map(t => {{
    const yy = pad.t + innerH * (1 - t);
    const label = Math.round(maxY * t);
    return `<line x1="${{pad.l}}" y1="${{yy}}" x2="${{W-pad.r}}" y2="${{yy}}" stroke="var(--border)"/>` +
      `<text x="${{pad.l-8}}" y="${{yy+4}}" text-anchor="end" fill="var(--muted)" font-size="11">${{label}}</text>`;
  }}).join("");
  const paths = series.map(s => {{
    const pts = s.data.map((v, i) => `${{x(i)}},${{y(v == null ? 0 : v)}}`).join(" ");
    const color = tones[s.tone] || "var(--fg)";
    return `<polyline fill="none" stroke="${{color}}" stroke-width="2.5" points="${{pts}}"/>` +
      s.data.map((v, i) => v == null ? "" :
        `<circle cx="${{x(i)}}" cy="${{y(v)}}" r="3.5" fill="${{color}}"/>`).join("");
  }}).join("");
  const labels = cats.map((c, i) =>
    `<text x="${{x(i)}}" y="${{H-10}}" text-anchor="middle" fill="var(--muted)" font-size="11">${{esc(c)}}</text>`
  ).join("");
  const legend = series.map(s =>
    `<span><i style="background:${{tones[s.tone]||'var(--fg)'}}"></i>${{esc(s.name)}}</span>`
  ).join("");
  return `<div class="chart"><svg viewBox="0 0 ${{W}} ${{H}}" role="img" aria-label="Latency chart">${{grid}}${{paths}}${{labels}}</svg><div class="legend">${{legend}}</div></div>`;
}}

function barChart(series, cats, height) {{
  const W = 880, H = height, pad = {{ t: 16, r: 16, b: 36, l: 56 }};
  const vals = series.flatMap(s => s.data.filter(v => v != null));
  const maxY = Math.max(...vals, 1) * 1.08;
  const innerW = W - pad.l - pad.r, innerH = H - pad.t - pad.b;
  const groupW = innerW / cats.length;
  const barW = Math.max(4, (groupW * 0.7) / series.length);
  const grid = [0, 0.25, 0.5, 0.75, 1].map(t => {{
    const yy = pad.t + innerH * (1 - t);
    const label = (maxY * t).toFixed(t === 0 || t === 1 ? 0 : 1);
    return `<line x1="${{pad.l}}" y1="${{yy}}" x2="${{W-pad.r}}" y2="${{yy}}" stroke="var(--border)"/>` +
      `<text x="${{pad.l-8}}" y="${{yy+4}}" text-anchor="end" fill="var(--muted)" font-size="11">${{label}}</text>`;
  }}).join("");
  let bars = "";
  cats.forEach((c, i) => {{
    series.forEach((s, si) => {{
      const v = s.data[i] == null ? 0 : s.data[i];
      const bh = (v / maxY) * innerH;
      const bx = pad.l + i * groupW + groupW * 0.15 + si * barW;
      const by = pad.t + innerH - bh;
      bars += `<rect x="${{bx}}" y="${{by}}" width="${{barW}}" height="${{bh}}" fill="${{tones[s.tone]||'var(--fg)'}}" rx="2"/>`;
    }});
  }});
  const labels = cats.map((c, i) =>
    `<text x="${{pad.l + i * groupW + groupW/2}}" y="${{H-10}}" text-anchor="middle" fill="var(--muted)" font-size="11">${{esc(c)}}</text>`
  ).join("");
  const legend = series.map(s =>
    `<span><i style="background:${{tones[s.tone]||'var(--fg)'}}"></i>${{esc(s.name)}}</span>`
  ).join("");
  return `<div class="chart"><svg viewBox="0 0 ${{W}} ${{H}}" role="img" aria-label="RPS chart">${{grid}}${{bars}}${{labels}}</svg><div class="legend">${{legend}}</div></div>`;
}}

function table(headers, rows, numCols) {{
  const th = headers.map((h, i) =>
    `<th class="${{numCols.includes(i) ? "num" : ""}}">${{esc(h)}}</th>`).join("");
  const body = rows.map(r =>
    `<tr>${{r.map((c, i) =>
      `<td class="${{numCols.includes(i) ? "num" : ""}}">${{esc(c)}}</td>`).join("")}}</tr>`
  ).join("");
  return `<table><thead><tr>${{th}}</tr></thead><tbody>${{body}}</tbody></table>`;
}}

const app = document.getElementById("app");
const failTone = data.headline.httpFailTone === "danger" ? "danger" : "success";
app.innerHTML = `
  <h1>Performance testing results</h1>
  <p class="muted">Profile ${{esc(data.profileName)}}. ${{esc(data.description)}} Compute: ${{esc(data.computeLabels)}}. Locust user steps: ${{esc(data.locustSteps.join(" → "))}}.</p>
  <div class="pills">
    <span class="pill">HTTP vs SETTLE split</span>
    <span class="pill">RLUSD burn p50 ${{esc(data.burnP50)}} s / p95 ${{esc(data.burnP95)}} s</span>
  </div>
  <div class="callout">${{esc(data.bottleneck)}}</div>
  <div class="stats">
    <div class="stat danger"><div class="v">${{esc(data.headline.worstHttpMedian)}}</div><div class="l">Worst HTTP median @ 10 users</div></div>
    <div class="stat success"><div class="v">${{esc(data.headline.bestHttpMedian)}}</div><div class="l">Best HTTP median @ 10 users</div></div>
    <div class="stat"><div class="v">${{esc(data.headline.peakHttpRps)}}</div><div class="l">Peak HTTP requests/s</div></div>
    <div class="stat"><div class="v">${{esc(data.headline.peakSettleRps)}}</div><div class="l">Peak settle throughput (end-to-end /s)</div></div>
  </div>
  <section>
    <h2>API response times under concurrent use</h2>
    <p class="muted">HTTP-only median latency (SETTLE events excluded) as Locust ramps concurrent users. One series per compute config. Users on the x-axis; median ms on the y-axis.</p>
    ${{lineChart(data.latencySeries, data.userCats, 280)}}
  </section>
  <section>
    <h2>Requests processed per second</h2>
    <p class="muted">HTTP request rate (SETTLE excluded) at each user-step plateau.</p>
    ${{barChart(data.rpsSeries, data.userCats, 260)}}
  </section>
  <section>
    <h2>Settlement: queue throughput, RLUSD time, success rates</h2>
    <p class="muted">Message-queue throughput is the Locust SETTLE “end to end” rate (settlements per second). RLUSD processing time uses the profile’s calibrated Testnet burn plus in-run “chain + confirm” medians under load.</p>
    <div class="stats">
      <div class="stat"><div class="v">${{esc(data.burnP50)}} s</div><div class="l">Calibrated RLUSD burn p50 (Testnet)</div></div>
      <div class="stat"><div class="v">${{esc(data.burnP95)}} s</div><div class="l">Calibrated RLUSD burn p95 (Testnet)</div></div>
      <div class="stat ${{failTone}}"><div class="v">${{esc(data.headline.httpFailPct)}}</div><div class="l">HTTP failure rate (all compute)</div></div>
    </div>
    ${{table(
      ["Compute", "Settle /s @ peak users", "Chain+confirm median", "HTTP fail %", "Settle fail %"],
      data.settleRows,
      [1, 2, 3, 4]
    )}}
  </section>
  ${{data.endpointRows.length ? `
  <section>
    <h2>Slowest HTTP endpoints @ 10 users (baseline compute)</h2>
    ${{table(
      ["Endpoint", "Median (ms)", "Requests", "Failures"],
      data.endpointRows,
      [1, 2, 3]
    )}}
  </section>` : ""}}
  <footer>Generated by tools/loadtest/to_canvas.py from Locust results. Open this file in a browser.</footer>
`;
</script>
</body>
</html>
"""


def _esc(value: object) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _user_categories(summary: RunSummary) -> list[int]:
    if summary.locust_steps:
        return list(summary.locust_steps)
    users: set[int] = set()
    for c in summary.compute:
        for p in c.plateaus:
            users.add(p.users)
    return sorted(users)


def _latency_series(summary: RunSummary, users: list[int]) -> list[dict]:
    tones = ("danger", "success", "info", "warning")
    series = []
    for i, c in enumerate(summary.compute):
        by_u = {p.users: p.http_median_ms for p in c.plateaus}
        series.append(
            {
                "name": f"{c.name} HTTP median (ms)",
                "data": [by_u.get(u) for u in users],
                "tone": tones[i % len(tones)],
            }
        )
    return series


def _rps_series(summary: RunSummary, users: list[int]) -> list[dict]:
    tones = ("danger", "success", "info", "warning")
    series = []
    for i, c in enumerate(summary.compute):
        by_u = {p.users: p.http_rps for p in c.plateaus}
        series.append(
            {
                "name": f"{c.name} HTTP req/s",
                "data": [by_u.get(u) for u in users],
                "tone": tones[i % len(tones)],
            }
        )
    return series


def _fmt_ms(value: float | None) -> str:
    if value is None:
        return "—"
    if value >= 1000:
        return f"{value / 1000:.1f} s"
    return f"{value:.0f} ms"


def _headline_stats(summary: RunSummary) -> dict:
    medians_at_10: list[tuple[str, float]] = []
    for c in summary.compute:
        p = next((x for x in c.plateaus if x.users == 10), None)
        if p and p.http_median_ms is not None:
            medians_at_10.append((c.name, p.http_median_ms))
    worst = max(medians_at_10, key=lambda t: t[1]) if medians_at_10 else None
    best = min(medians_at_10, key=lambda t: t[1]) if medians_at_10 else None
    peak_rps = max((c.peak_http_rps for c in summary.compute), default=0.0)
    peak_settle = max(
        (c.settle_throughput_at_peak_users for c in summary.compute), default=0.0
    )
    # Prefer highest-fail compute for the headline fail %
    http_fail = max((c.http_fail_pct for c in summary.compute), default=0.0)
    return {
        "worstHttpMedian": _fmt_ms(worst[1] if worst else None),
        "bestHttpMedian": _fmt_ms(best[1] if best else None),
        "peakHttpRps": f"{peak_rps:.1f}/s",
        "peakSettleRps": f"{peak_settle:.2f}/s",
        "httpFailPct": f"{http_fail:.1f}%",
        "httpFailTone": "danger" if http_fail >= 1 else "success",
    }


def _settle_table_rows(summary: RunSummary) -> list[list[str]]:
    rows = []
    for c in summary.compute:
        peak = c.plateaus[-1] if c.plateaus else None
        chain = peak.chain_confirm_median_ms if peak else None
        rows.append(
            [
                c.name,
                f"{c.settle_throughput_at_peak_users:.2f}",
                _fmt_ms(chain),
                f"{c.http_fail_pct:.1f}%",
                f"{c.settle_fail_pct:.1f}%",
            ]
        )
    return rows


def _endpoint_table_rows(summary: RunSummary) -> list[list[str]]:
    if not summary.compute:
        return []
    # Baseline = first compute step (low CPU first in sweep profiles).
    baseline = summary.compute[0]
    return [
        [
            e.name,
            f"{e.median_ms:.0f}",
            str(e.requests),
            str(e.failures),
        ]
        for e in baseline.endpoints_at_10
    ]


if __name__ == "__main__":
    raise SystemExit(main())
